# Generated by Django 4.2.5 on 2023-10-07 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiling", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="nickname",
            field=models.CharField(default="", max_length=20),
        ),
    ]
