# Generated by Django 4.2.5 on 2023-10-07 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiling", "0002_userprofile_nickname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="nickname",
            field=models.CharField(max_length=20),
        ),
    ]
