# Generated by Django 4.2.5 on 2023-10-03 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SearchForLover", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="requestforlovermodel",
            name="request_message",
            field=models.TextField(blank=True),
        ),
    ]
