# Generated by Django 4.2.5 on 2023-10-04 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SearchForLover", "0002_requestforlovermodel_request_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="requestforlovermodel",
            name="isRequestSent",
            field=models.BooleanField(default=False),
        ),
    ]
