# Generated by Django 4.2.5 on 2023-10-05 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("SearchForLover", "0003_requestforlovermodel_isrequestsent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="requestforlovermodel",
            name="isRequestSent",
        ),
    ]
