# Generated by Django 4.2.5 on 2023-10-10 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("profiling", "0004_userprofile_photo"),
        ("SearchForLover", "0004_remove_requestforlovermodel_isrequestsent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="requestforlovermodel",
            name="receiver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="receiver_id",
                to="profiling.userprofile",
            ),
        ),
        migrations.AlterField(
            model_name="requestforlovermodel",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sender_id",
                to="profiling.userprofile",
            ),
        ),
        migrations.CreateModel(
            name="UnsentRequestModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("request_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "receiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unsent_receiver_id",
                        to="profiling.userprofile",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unsent_sender_id",
                        to="profiling.userprofile",
                    ),
                ),
            ],
        ),
    ]
